spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes: # 路由可以有多个
        - id: service-autodeliver-router # 我们自定义的路由，ID，保持唯一
          uri: lb://lagou-service-autodeliver #目标服务地址  动态路由： uri配置的应该是一个服务名称 而不是具体实例地址 lb://从注册中心获取
          predicates:
            - Path=/autodeliver/** #断言：路由条件，Predicate 接受一个输入参数 返回一个布尔结果。
          filters: #单路由过滤器
            - StripPrefix=1 #去除第一个字符串
        - id: # 多个路由